description: >- # this means to ignore newlines until "baseurl:"
   Personal Website
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  paredesroger

plugins:
  - jekyll-relative-links

title: Roger Paredes

relative_links:
  enabled: true
  collections: true

remote_theme: jekyll/minima

minima:
  social_links:
    - { platform: google_scholar,  user_url: "https://scholar.google.com/citations?user=mm0pN8oAAAAJ"}
    - { platform: researchgate, user_url: "https://www.researchgate.net/profile/Roger-Paredes-2"}
    - { platform: twitter, user_url: "https://x.com/paredesrogerl" }
    - { platform: github, user_url: "https://github.com/paredesroger/" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/paredesroger/" }
    

# Google Analytics
google_analytics: G-15K5ZW25WJ
